import Footer from '@/components/navbar/footer/Footer';
import './globals.css';
import { Inter, Roboto, Poppins } from 'next/font/google';
import NavBar from '@/components/navbar/footer/NavBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <>
      <div className={inter.className}>
        <div className="container">        
        <NavBar />
        {children}
        <Footer />
      </div>
      </div>
    </>
  );
}
